# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# CONFIGS GENERAL
neo_version_range=[21.1.233,)
minecraft_version_range=[1.21.1]
loader_version_range=[4,)

# CONFIGS MOD
mod_version=1.0.0
mod_id=celesthyd
mod_group=net.sirgrantd.celesthyd
mod_name=Celesthyd Lib
mod_license=SirGrantd License
mod_authors=SirGrantd
mod_description=Mod Library for SirGrantd's Mods.
logo_file: logo.png
